name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: list and read files
      run: |
        echo "My first GitHub Actions job"
        ls -ltr
        cat README.md

    - name: generate ASCII artwork
      run: cowsay -f tiger "Run for cover, Iam tiger.....RAWR" >>  tiger.txt

    # - name: List Files
    #   run: ls -la

    # - name: Read File
    #   run: cat README.md