name: Generate ASCII Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute ascii shell script
        run: |
            chmod +x ascii.sh
            ./ascii-script.sh

      - name: List repository files
        run: ls -ltra